### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by sydev** [evilebottnawi/favicons#200]
I use the gulp wrapper `gulp-favicons` to automatically build my favicons. Locally on my MacBook everything works well, but when my build process is running on my server, the following error occurs:

```
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:841:14)
Emitted 'error' event at:
    at onwriteError (_stream_writable.js:427:12)
    at onwrite (_stream_writable.js:449:5)
    at _destroy (internal/streams/destroy.js:39:7)
    at Socket._destroy (net.js:545:3)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:843:10)
```

My config:

```
appName: 'myapp',
appDescription: 'myapp',
developerName: 'myname',
developerURL: 'myurl',
background: '#fff',
theme_color: '#fff',
path: '/',
display: 'standalone',
orientation: 'portrait',
start_url: '/?homescreen=1',
version: '1.0',
logging: false,
online: false,
preferOnline: false,
icons: { 
  android: true,
  appleIcon: true,
  appleStartup: true,
  coast: { offset: 25 },
  favicons: true,
  firefox: true,
  windows: true,
  yandex: true
}
```

I got no clue, can someone help?

OS: Ubuntu 16.04
Node: 9.8.0
npm: 5.7.1

**Comment by evilebottnawi** [comment]
@sydev please update to latest version, feel free to recreate/reopen issue if still regression. Thanks!
